# Generated by Django 2.1.3 on 2020-03-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=models.ImageField(blank=True, upload_to='')),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image_file_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
