# Generated by Django 2.1.3 on 2020-03-11 03:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200311_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image_file_path',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
